apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-example
spec:
  rules:
    - host: app-example.app-example.svc
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app-example
                port:
                  name: http
