apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: jaeger-operator-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: jaeger-operator/jaeger-operator-serving-cert
